name: pomo
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  change_app_package_name: ^1.4.0
  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  introduction_screen: ^3.1.14
  smooth_page_indicator: ^1.2.0+3
  get_storage: ^2.1.1
  simple_icons: ^10.1.3
  elegant_notification: ^2.3.0
  intl_phone_field: ^3.2.0 
  flutter_svg_provider: ^1.0.7
  iconsax: ^0.0.8
  otp_text_field: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1



flutter_launcher_icons:
  android: true
  image_path: "assets/logo/pomo_logo.png"
  adaptive_icon_background: "#FF6267"
  adaptive_icon_foreground: "assets/logo/pomo_logo_foreground.png"
  
  
  flutter_lints: ^5.0.0





flutter:

  assets:
    - "assets/logo/"
    - "assets/images/"
    - "assets/animations/"
  
  
  uses-material-design: true
  
  
